# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatable',
            name='tableLink',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
